import os, json, base64, mimetypes
from pathlib import Path
import requests
from dotenv import load_dotenv
from pypdf import PdfReader

load_dotenv()
API_KEY = os.getenv('NVIDIA_API_KEY')
if not API_KEY:
    raise RuntimeError('NVIDIA_API_KEY is missing. Create .env first.')

API_URL = 'https://integrate.api.nvidia.com/v1/chat/completions'
MODEL = 'meta/llama-3.2-90b-vision-instruct'
MISSION_DOCUMENT = 'mission_guide.pdf'
MAT_IMAGE = 'grc_mat.jpg'

SYSTEM_PROMPT = '''You are the mission-planning AI for XploreBot.
Read the official GRC mission document and the attached competition mat.
The document defines the rules; the image defines the physical layout.
Never invent paths. XploreBot commands are S=straight, L=left 90 degrees, R=right 90 degrees, X=stop.
Return ONLY JSON with keys mission_understanding, map_understanding, route, checkpoints, confidence, warnings.
Route may contain only S,L,R,X and X must be final. If no reliable route exists, return an empty route and explain why.'''


def read_document(name):
    p = Path(name)
    if p.suffix.lower() == '.pdf':
        return '\n\n'.join((x.extract_text() or '') for x in PdfReader(str(p)).pages)
    return p.read_text(encoding='utf-8')

def image_data(name):
    p = Path(name)
    mime = mimetypes.guess_type(str(p))[0] or 'image/jpeg'
    return 'data:' + mime + ';base64,' + base64.b64encode(p.read_bytes()).decode()

mission = read_document(MISSION_DOCUMENT)
image = image_data(MAT_IMAGE)
payload = {'model': MODEL, 'messages': [
    {'role':'system','content':SYSTEM_PROMPT},
    {'role':'user','content':[
        {'type':'text','text':'Analyze the GRC mission using this official document:\n\n' + mission},
        {'type':'image_url','image_url':{'url':image}}
    ]}
], 'temperature':0.1, 'max_tokens':2048, 'stream':False}

r = requests.post(API_URL, headers={'Authorization':'Bearer ' + API_KEY, 'Accept':'application/json', 'Content-Type':'application/json'}, json=payload, timeout=120)
r.raise_for_status()
raw = r.json()
Path('ai_response.json').write_text(json.dumps(raw, indent=2), encoding='utf-8')
text = raw['choices'][0]['message']['content'].strip().replace('```json','').replace('```','').strip()
start, end = text.find('{'), text.rfind('}')
result = json.loads(text[start:end+1])

route = result.get('route', [])
if not route or any(x not in {'S','L','R','X'} for x in route) or route[-1] != 'X' or 'X' in route[:-1]:
    raise RuntimeError('AI route rejected: ' + str(route))

Path('ai_mission.py').write_text(
    '# Generated by GRC XploreBot AI Planner\n' +
    'MISSION = ' + repr(route) + '\n' +
    'CHECKPOINTS = ' + repr(result.get('checkpoints', [])) + '\n' +
    'AI_CONFIDENCE = ' + repr(result.get('confidence', 0.0)) + '\n' +
    'WARNINGS = ' + repr(result.get('warnings', [])) + '\n',
    encoding='utf-8'
)

print('Route:', route)
print('Checkpoints:', result.get('checkpoints', []))
print('Confidence:', result.get('confidence', 0.0))
print('Generated ai_mission.py')